# useErrorBoundary

`useErrorBoundary` is a hook that lets you retrieve the caught `error` and allow `recovery` within the `fallback` component.

<hr/>

### Type & Parameters

```ts
type UseErrorBoundary = [Error | string, () => void];

function useErrorBoundary(): UseErrorBoundary;
```

<br/>

### Returns

returns an array of two elements:

- `error` : contain the thrown error
- `recover` : a function that will attempt to recover from the error.

<br/>

### Notes ⚠️

- Throws if called outside of the fallback component.
- Throws if called from a composable.

<hr/>

### Example

<iframe src="https://stackblitz.com/edit/ruvy-a3desu?embed=1&file=src%2Fmain.tsx&hideExplorer=1&hideNavigation=1" class="stackblitz"></iframe>
